contextId=contextid
contextData=contextdata
contextIdType=contextidtype
rootOrgId=rootorgid
profileDetails=profiledetails
contextid=contextId
contextidtype=contextIdType
contextdata=contextData
isarchived=isArchived
planid=planId
orgscope=orgScope
contentlist=contentList
contenttype=contentType
draftdata=draftData
enddate=endDate
isapar=isApar
orgidlist=orgIdList
createat=createdAt
createdby=createdBy
updatedat=updatedAt
updatedby=updatedBy
firstname=firstName
userid=userId
orgid=orgId
assignmenttype=assignmentType
assignmenttypeinfo=assignmentTypeInfo
rootorgid=rootOrgId
additionalattributes=additionalAttributes
content_id=contentId
request_id=requestId
retirement_date=retirementDate
updated_at=updatedAt
batchid=batchId
filename=fileName
filepath=filePath
createdon=createdOn
competency_subtheme_id=competencySubThemeId
user_id=userId
competency_theme_id=competencyThemeId
competency_area_id=competencyAreaId
competency_details=competencyDetails
failedrecordscount=failedRecordsCount
successfulrecordscount=successfulRecordsCount
totalrecords=totalRecords